# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Carrier',
            fields=[
                ('carrierNumber', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Iteration',
            fields=[
                ('iterationNumber', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_IterationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedAverage', models.FloatField()),
                ('accelerationAverage', models.FloatField()),
                ('energyConsumptionTotal', models.FloatField()),
                ('energyConsumptionAverage', models.FloatField()),
                ('fid_Carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Carrier')),
                ('fid_Iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Iteration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Session',
            fields=[
                ('sessionNumber', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_TimeStampData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.BigIntegerField()),
                ('positionOnDrive', models.FloatField()),
                ('positionAbsolute', models.FloatField()),
                ('speed', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('energyConsumption', models.FloatField()),
                ('fid_Carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Carrier')),
                ('fid_Iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Iteration')),
                ('fid_Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Session')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_iterationdata',
            name='fid_Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.tbl_Session'),
        ),
    ]
