###########################################################
# Dockerfile to run a Django-based web application
# Based on an Amos Web Service Base Image
############################################################

# Set the base image to use to Ubuntu
FROM osrgroup/amos-web-service-base-image:1.0 

#Define the Maintainer of the Image
MAINTAINER AMOS-TEAM-6
