# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('position', models.FloatField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.Carrier')),
            ],
        ),
    ]
