# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrier',
            fields=[
                ('carrierNumber', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='iteration',
            fields=[
                ('iterationNumber', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='iterationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('carrier', models.IntegerField()),
                ('iteration', models.IntegerField()),
                ('speedAverage', models.FloatField()),
                ('accelerationAverage', models.FloatField()),
                ('energyConsumptionTotal', models.FloatField()),
                ('energyConsumptionAverage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('sessionNumber', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='timestampdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('carrier', models.IntegerField()),
                ('iteration', models.IntegerField()),
                ('timeStamp', models.BigIntegerField()),
                ('positionOnDrive', models.FloatField()),
                ('positionAbsolute', models.FloatField()),
                ('speed', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('energyConsumption', models.FloatField()),
            ],
        ),
    ]
