#!/bin/bash
#
# Copyright 2016 The Open Source Research Group,
#                University of Erlangen-Nürnberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -ue

# setuser: Never run as root!
# authbind: Allows non-root processes to bind to privileged ports (80)
# --path: Make the web application available under a specific URL path
#   The $CONTEXT_PATH environment variable has to be specific when starting a
#   container (e.g. docker run ... -e CONTEXT_PATH=/ ... <image>)

exec /sbin/setuser www-data \
  authbind --deep \
    java -jar /usr/share/java/jetty-runner.jar \
    --port 80 \
    --path $CONTEXT_PATH \
    /web-service-assets/web-service.war
